### ISSUE TITLE
Update schedule?

### ISSUE THREAD

**Issue by ravwojdyla** [hugheylab/pmparser#53]
👋  first of all, thank you so much for all your hard work and making this resource/code available!
I have a question about the BigQuery data `pmdb-bq:pmdb.*`, it appears the last update was on the Jan 19, 2022. If you plan to update the data, I'm curious what's the update schedule like? I'm sorry if this is not the right place to ask this question.

**Comment by ravwojdyla** [comment]
Should have paid more attention to the details in the paper, from https://peerj.com/articles/11071/:

> To make PMDB more widely accessible, we also made it publicly available on Google BigQuery (https://console.cloud.google.com/bigquery?project=pmdb-bq&d=pmdb), which is designed for large-scale and high-speed analytics. With BigQuery, users can access PMDB without having to set up their own database server, and are responsible only for the costs of their queries. We plan to update both versions of PMDB monthly.

I'm curious, do you plan to resume monthly updates?

**Comment by jakejh** [comment]
Noted. Thanks for raising the issue! The update process has a couple steps that can't easily be automated, so to be honest, I've been waiting to see if anyone's actually using the database and would notice if the updates were less frequent. Moving forward, I'll plan to update pmdb monthly. 

I'll let you know when the next update finishes. The db needs to be rebuilt from scratch, because we updated pmparser to slightly improve the schema.

**Comment by ravwojdyla** [comment]
Thank you so much @jakejh! Looking forward to the update. Let me know if I can help in any way.

**Comment by jakejh** [comment]
Ok, pmdb is now updated on BigQuery!

The postgres dump of pmdb is not yet updated on Zenodo, because Zenodo's API seems to be having issues with uploads.

**Comment by ravwojdyla** [comment]
Amazing, thank you so much @jakejh!

**Comment by sitch** [comment]
I've been using it!

I have a private repo with a github workflow that:
- pings zenodo for the latest version 
- if it's outdated:
  - writes a manifest file
  - opens a git PR
  - builds a postgres container
  - tags a git release
 
If anyone wants to use it -- happy to open source the repo or container if there's interest?

**Comment by jakejh** [comment]
Ok, the latest postgres dump is now on Zenodo. Unfortunately, I had to upload the dump files individually, because Zenodo's API kept choking on the one tar file of 25 GB, and their "support" didn't live up to the name. Perhaps I'll come up with a better solution at some point, but this will have to do for now.
